FROM node:18-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install --production=false
COPY . .
COPY .env .
ARG VERSION=$(node -p "require('./package.json').version")
ARG BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
ENV REACT_APP_VERSION=$VERSION
ENV REACT_APP_BUILD_TIME=$BUILD_TIME
RUN npm run build
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]